from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import pandas as pd


def as_str(v) -> str:
    if v is None:
        return ""
    s = str(v)
    if s.lower() == "nan":
        return ""
    return s.strip()


def as_bool(v) -> bool:
    if isinstance(v, bool):
        return v
    s = as_str(v).lower()
    return s in {"1", "true", "yes", "y"}


def run_upload(ps_script: Path, row: pd.Series, datasource: str, username: str) -> tuple[int, str]:
    cmd = [
        "powershell",
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(ps_script),
        "-FilePath",
        as_str(row.get("local_file_path")),
        "-DatasourceName",
        datasource,
        "-UserName",
        username,
    ]

    pw_folder = as_str(row.get("pw_folder_path"))
    if pw_folder:
        cmd += ["-PWFolderPath", pw_folder]

    doc_name = as_str(row.get("document_name"))
    if doc_name:
        cmd += ["-DocumentName", doc_name]

    desc = as_str(row.get("description"))
    if desc:
        cmd += ["-Description", desc]

    version = as_str(row.get("version"))
    if version:
        cmd += ["-Version", version]

    app = as_str(row.get("application"))
    if app:
        cmd += ["-Application", app]

    attrs = as_str(row.get("attributes_json"))
    if attrs:
        # Accept either inline JSON or a JSON file path.
        if attrs.startswith("{"):
            attrs_path = ps_script.parent / "_tmp_upload_attrs.json"
            attrs_path.write_text(attrs, encoding="utf-8")
            cmd += ["-AttributesJson", str(attrs_path)]
        else:
            cmd += ["-AttributesJson", attrs]

    proc = subprocess.run(cmd, capture_output=True, text=True)
    output = (proc.stdout or "") + ("\n" + proc.stderr if proc.stderr else "")
    return proc.returncode, output


def main() -> int:
    parser = argparse.ArgumentParser(description="Upload ProjectWise files using a manifest Excel.")
    parser.add_argument("--manifest", required=True, help="Path to manifest Excel generated by generate_pw_upload_manifest.py")
    parser.add_argument(
        "--upload-script",
        default="Scripts/PWPS_Upload_PW.ps1",
        help="PowerShell upload script path",
    )
    parser.add_argument("--datasource", default="arcadis-uk-pw.bentley.com:arcadis-uk-07")
    parser.add_argument("--username", default="_asc_user_automation")
    parser.add_argument("--limit", type=int, default=0, help="Optional row limit for testing")
    args = parser.parse_args()

    manifest_path = Path(args.manifest).resolve()
    ps_script = Path(args.upload_script).resolve()

    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    if not ps_script.exists():
        raise FileNotFoundError(f"Upload script not found: {ps_script}")

    df = pd.read_excel(manifest_path, dtype=str)
    if df.empty:
        print("Manifest is empty. Nothing to upload.")
        return 1

    if "upload_enabled" not in df.columns:
        df["upload_enabled"] = True

    rows = df[df["upload_enabled"].map(as_bool)]
    if args.limit and args.limit > 0:
        rows = rows.head(args.limit)

    if rows.empty:
        print("No rows enabled for upload.")
        return 1

    results = []
    for i, (_, row) in enumerate(rows.iterrows(), start=1):
        local_file = as_str(row.get("local_file_path"))
        print(f"[{i}/{len(rows)}] Uploading: {local_file}")
        rc, out = run_upload(ps_script, row, args.datasource, args.username)
        ok = rc == 0
        print("SUCCESS" if ok else "FAILED")
        if not ok:
            print(out)
        results.append(
            {
                "local_file_path": local_file,
                "document_name": as_str(row.get("document_name")),
                "version": as_str(row.get("version")),
                "pw_folder_path": as_str(row.get("pw_folder_path")),
                "success": ok,
                "exit_code": rc,
                "output": out,
            }
        )

    result_df = pd.DataFrame(results)
    result_path = manifest_path.with_name(manifest_path.stem + "_upload_results.xlsx")
    result_df.to_excel(result_path, index=False)
    print(f"Wrote upload results: {result_path}")

    failed = int((~result_df["success"]).sum())
    if failed:
        print(f"Upload completed with failures: {failed}/{len(result_df)}")
        return 2

    print(f"Upload completed successfully: {len(result_df)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
